<a href="https://colab.research.google.com/github/Edwinshajan2006/data-science-/blob/main/fuctions%20using%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:

import numpy as np
#importing numpy

In [44]:
import pandas as pd
#importing panda


In [45]:
data=pd.read_excel("/content/numpy_sales_dataset 1.xlsx")
#to link excel to the program inside the brackets we are giving the location path

In [46]:
data.head()
#to read the starting 5 rows

,order_id,region,product,units_sold,unit_price,discount,revenue,profit,month,rating
0,1,West,Phone,6,2999,0,17994,14076,Jun,1
1,2,East,Phone,83,2113,10,175379,170710,Mar,3
2,3,North,Tablet,14,1826,10,25564,21134,Feb,3
3,4,East,Accessory,62,3377,10,209374,205901,Feb,4
4,5,East,Phone,58,861,15,49938,45446,Feb,3


In [47]:
data.tail()
#to read the last 5 rows;

,order_id,region,product,units_sold,unit_price,discount,revenue,profit,month,rating
45,46,South,Laptop,70,4433,0,310310,307384,Feb,5
46,47,South,Tablet,65,3180,5,206700,202332,Jan,2
47,48,North,Phone,61,4137,0,252357,249311,Feb,3
48,49,South,Accessory,8,4434,15,35472,32762,Jun,2
49,50,South,Phone,25,2629,5,65725,61723,Jun,4


In [48]:
col = ["order_id","units_sold","unit_price","discount","revenue","profit","rating"] #storing numberical columns
num_array=data[col].to_numpy() #converting numerical array to numpy

#key error found via execution

In [49]:
num_array
#all the outputs without headings

array([[     1,      6,   2999,      0,  17994,  14076,      1],
       [     2,     83,   2113,     10, 175379, 170710,      3],
       [     3,     14,   1826,     10,  25564,  21134,      3],
       [     4,     62,   3377,     10, 209374, 205901,      4],
       [     5,     58,    861,     15,  49938,  45446,      3],
       [     6,     43,   3222,      5, 138546, 134662,      4],
       [     7,     29,   4190,     15, 121510, 117649,      1],
       [     8,     30,   2352,      0,  70560,  67946,      1],
       [     9,     35,   4021,     15, 140735, 138301,      3],
       [    10,     89,   3478,      5, 309542, 305131,      1],
       [    11,     86,   1749,     10, 150414, 146247,      5],
       [    12,     59,   1674,     15,  98766,  97996,      3],
       [    13,     39,   4334,     10, 169026, 167644,      4],
       [    14,     65,   2490,     10, 161850, 159121,      3],
       [    15,     64,   3436,      0, 219904, 215675,      4],
       [    16,     69,  

In [50]:
#2 a
num_array.shape

(50, 7)

In [51]:
#2 b
num_array.ndim

2

In [52]:
#2 c
num_array.dtype

dtype('int64')

In [53]:
#3 a
units_sold=['units_sold']
units_sold_array=data[units_sold].to_numpy()
units_sold_array


array([[ 6],
       [83],
       [14],
       [62],
       [58],
       [43],
       [29],
       [30],
       [35],
       [89],
       [86],
       [59],
       [39],
       [65],
       [64],
       [69],
       [64],
       [46],
       [ 8],
       [ 5],
       [41],
       [72],
       [38],
       [46],
       [64],
       [52],
       [21],
       [52],
       [ 5],
       [12],
       [56],
       [56],
       [47],
       [86],
       [95],
       [38],
       [81],
       [70],
       [42],
       [64],
       [93],
       [11],
       [11],
       [70],
       [49],
       [70],
       [65],
       [61],
       [ 8],
       [25]])

In [54]:
#3 b
unit_price=['unit_price']
unit_price_array=data[unit_price].to_numpy()
unit_price_array

array([[2999],
       [2113],
       [1826],
       [3377],
       [ 861],
       [3222],
       [4190],
       [2352],
       [4021],
       [3478],
       [1749],
       [1674],
       [4334],
       [2490],
       [3436],
       [4135],
       [ 938],
       [1832],
       [4234],
       [1935],
       [1104],
       [3963],
       [2043],
       [1673],
       [2134],
       [4877],
       [1678],
       [2767],
       [3397],
       [3675],
       [1827],
       [2364],
       [3658],
       [3462],
       [1238],
       [3272],
       [3682],
       [2019],
       [2982],
       [2613],
       [ 827],
       [1026],
       [2507],
       [1931],
       [ 654],
       [4433],
       [3180],
       [4137],
       [4434],
       [2629]])

In [55]:
#4 a

sum_units_sold=np.sum(units_sold_array)
sum_units_sold

np.int64(2455)

In [56]:
#4 b
avg_units_sold=np.mean(units_sold_array)
avg_units_sold

np.float64(49.1)

In [59]:

#4 c a
min_units_sold=np.min(units_sold_array)
min_units_sold




np.int64(5)

In [60]:
# 4 c b
max_units_sold=np.max(units_sold_array)
max_units_sold

np.int64(95)

In [61]:
#5 a
total_revenue=np.sum(num_array[])
total_revenue

np.int64(6328203)